# Fly.io deployment configuration
app = "scottish-adventure"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/ping"

[processes]
  app = "npm run start"

[[statics]]
  guest_path = "/app/dist/spa"
  url_prefix = "/"
